#pragma once

// DON'T EDIT - This file is auto generated by sharpmake
// NOLINTBEGIN

namespace rex
{
  enum class MountingPoint
  {
    // MountingPoint values for RexEngine
    // generated from D:\Engines\Rex\config\1_engine\rex_engine\generation.json
    Logs,

  };
} // namespace rex
// NOLINTEND
