#pragma once

// DON'T EDIT - This file is auto generated by sharpmake
// NOLINTBEGIN

namespace rex
{
  enum class MountRoot
  {
    // mount roots for RexEngine
    Logs,
  };
} // namespace rex
// NOLINTEND
