#pragma once

// DON'T EDIT - This file is auto generated by sharpmake
// Generated from code generation key 'MemoryTags'
// NOLINTBEGIN

namespace rex
{
  enum class MemoryTag
  {
    // MemoryTag values for RexEngine
    Global,
    Engine,
    FileIO,
    StringPool,
    Renderer,
 
    // MemoryTag values for Regina
    Editor,
 
    // MemoryTag values for ConsoleApp
    ConsoleApp,
 
    // MemoryTag values for Pokemon
    Pokemon,
 
    // MemoryTag values for RexWindows
    Windows,
 
  };
} // namespace rex
// NOLINTEND
