#pragma once

// DON'T EDIT - This file is auto generated by sharpmake
// Generated from code generation key 'CommandLineArgs'
// NOLINTBEGIN

#include "rex_engine/cmdline/cmdline.h"
#include "rex_std/array.h"
namespace rex
{
  inline rsl::array g_command_line_args = 
  {
    // cmdline::Argument values for RexEngine - using code generation key: 'CommandLineArgs'
    cmdline::Argument{ "Root", "The directory to initialize the vfs with. this is similar as setting the working root directory", "RexEngine" },
    cmdline::Argument{ "Help", "This will list all command line arguments for the executable", "RexEngine" },
    cmdline::Argument{ "LogLevel", "Specify log level per logger (eg. -LogLevel=Engine=trace,Renderer=info)", "RexEngine" },
    cmdline::Argument{ "BreakOnBoot", "Break on boot so you can attach a debugger", "RexEngine" },
    cmdline::Argument{ "AttachOnBoot", "Attach the debugger on boot", "RexEngine" },
 
    // cmdline::Argument values for RexEngineUnitTest - using code generation key: 'CommandLineArgs'
    cmdline::Argument{ "ExampleArgument", "Example argument, not used for anything other than testing if it works.", "RexEngineUnitTest" },
    cmdline::Argument{ "ExampleArgument2", "Example argument, not used for anything other than testing if it works.", "RexEngineUnitTest" },
    cmdline::Argument{ "ExampleArgumentWithEqual", "Example argument with equal sign. not used for anything other than testing if it works", "RexEngineUnitTest" },
 
    // cmdline::Argument values for Pokemon - using code generation key: 'CommandLineArgs'
    cmdline::Argument{ "StartLevel", "The level to load on start.", "Pokemon" },
    cmdline::Argument{ "StartMap", "The map to load on start.", "Pokemon" },
    cmdline::Argument{ "StartupSaveFile", "The startup save file to load instead of the default one.", "Pokemon" },
 
    // cmdline::Argument values for Regina - using code generation key: 'CommandLineArgs'
    cmdline::Argument{ "project", "The project to load by the editor", "Regina" },
 
  };
} // namespace rex
// NOLINTEND
