#include <vector>
#include <string>

enum class CmdType {
  Tempo,
  Volume,
  DutyCycle,
  TogglePerfectPitch,
  NoteType,
  Octave,
  Note,
  Rest,
  LoopStart,
  SoundLoop
};

struct Event {
  CmdType type;
  std::string note;
  std::vector<int> args;
};

namespace Music_DefeatedTrainer_Ch1 {
  static const std::vector<Event> data = {
      {CmdType::Tempo, "", {224}},
      {CmdType::Volume, "", {7,7}},
      {CmdType::DutyCycle, "", {2}},
      {CmdType::TogglePerfectPitch, ""},
      {CmdType::Tempo, "", {224}},
      {CmdType::NoteType, "", {4,10,2}},
      {CmdType::Octave, "", {4}},
      {CmdType::Note, "D_", {2}},
      {CmdType::Tempo, "", {224}},
      {CmdType::NoteType, "", {4,10,2}},
      {CmdType::Note, "D_", {2}},
      {CmdType::Note, "D_", {2}},
      {CmdType::Note, "D_", {2}},
      {CmdType::Octave, "", {3}},
      {CmdType::Note, "A_", {2}},
      {CmdType::Octave, "", {4}},
      {CmdType::Note, "D_", {2}},
      {CmdType::NoteType, "", {4,11,3}},
      {CmdType::Note, "F#", {12}},
      {CmdType::DutyCycle, "", {1}},
      {CmdType::Tempo, "", {224}},

      {CmdType::LoopStart, ".mainloop"},

      {CmdType::NoteType, "", {4,6,3}},
      {CmdType::Octave, "", {3}},
      {CmdType::Note, "A_", {6}},
      {CmdType::Note, "F#", {3}},
      {CmdType::Note, "A_", {3}},
      {CmdType::Note, "B_", {6}},
      {CmdType::Note, "G#", {3}},
      {CmdType::Note, "B_", {3}},
      {CmdType::Octave, "", {4}},
      {CmdType::Note, "C#", {3}},
      {CmdType::Octave, "", {3}},
      {CmdType::Note, "B_", {3}},
      {CmdType::Note, "A_", {3}},
      {CmdType::Note, "G_", {3}},
      {CmdType::Note, "A_", {3}},
      {CmdType::Note, "B_", {3}},
      {CmdType::Note, "A_", {3}},
      {CmdType::Note, "G_", {3}},
      {CmdType::Note, "A_", {6}},
      {CmdType::Note, "F#", {3}},
      {CmdType::Note, "A_", {3}},
      {CmdType::Note, "B_", {6}},
      {CmdType::Note, "G#", {3}},
      {CmdType::Note, "B_", {3}},
      {CmdType::Octave, "", {4}},
      {CmdType::Note, "C#", {3}},
      {CmdType::Note, "D_", {3}},
      {CmdType::Note, "E_", {3}},
      {CmdType::Note, "F#", {3}},
      {CmdType::Note, "C#", {3}},
      {CmdType::Octave, "", {3}},
      {CmdType::Note, "B_", {3}},
      {CmdType::Note, "A_", {3}},
      {CmdType::Octave, "", {4}},
      {CmdType::Note, "C#", {3}},
      {CmdType::Octave, "", {3}},
      {CmdType::Note, "A_", {6}},
      {CmdType::Note, "F#", {3}},
      {CmdType::Note, "A_", {3}},
      {CmdType::Note, "B_", {6}},
      {CmdType::Note, "G#", {3}},
      {CmdType::Note, "B_", {3}},
      {CmdType::Octave, "", {4}},
      {CmdType::Note, "C_", {6}},
      {CmdType::Octave, "", {3}},
      {CmdType::Note, "A_", {3}},
      {CmdType::Octave, "", {4}},
      {CmdType::Note, "C_", {3}},
      {CmdType::Note, "D_", {3}},
      {CmdType::Octave, "", {3}},
      {CmdType::Note, "B_", {3}},
      {CmdType::Octave, "", {4}},
      {CmdType::Note, "D_", {6}},
      {CmdType::Note, "C#", {3}},
      {CmdType::Octave, "", {3}},
      {CmdType::Note, "B_", {3}},
      {CmdType::Note, "A_", {3}},
      {CmdType::Note, "G_", {3}},
      {CmdType::Note, "F#", {3}},
      {CmdType::Note, "G_", {3}},
      {CmdType::Note, "A_", {3}},
      {CmdType::Note, "B_", {3}},
      {CmdType::Note, "A_", {3}},
      {CmdType::Note, "G_", {3}},
      {CmdType::Note, "F#", {3}},
      {CmdType::Note, "E_", {3}},
      {CmdType::Note, "F#", {3}},
      {CmdType::Note, "G_", {3}},
      {CmdType::Note, "A_", {3}},
      {CmdType::Note, "B_", {3}},

      {CmdType::SoundLoop, ".mainloop", {0}}
  };
}

namespace Music_DefeatedTrainer_Ch2 {
  static const std::vector<Event> data = {
      {CmdType::DutyCycle, "", {2}},
      {CmdType::NoteType, "", {4,12,3}},
      {CmdType::Octave, "", {4}},
      {CmdType::Note, "A_", {2}},
      {CmdType::Note, "A_", {2}},
      {CmdType::Note, "A_", {2}},
      {CmdType::Note, "A_", {2}},
      {CmdType::Note, "B_", {2}},
      {CmdType::Octave, "", {5}},
      {CmdType::Note, "C#", {2}},
      {CmdType::NoteType, "", {4,12,4}},
      {CmdType::Note, "D_", {12}},

      {CmdType::LoopStart, ".mainloop"},

      {CmdType::NoteType, "", {4,8,5}},
      {CmdType::Octave, "", {4}},
      {CmdType::Note, "D_", {6}},
      {CmdType::Octave, "", {3}},
      {CmdType::Note, "A_", {3}},
      {CmdType::Octave, "", {4}},
      {CmdType::Note, "D_", {3}},
      {CmdType::Note, "E_", {6}},
      {CmdType::Octave, "", {3}},
      {CmdType::Note, "B_", {3}},
      {CmdType::Octave, "", {4}},
      {CmdType::Note, "E_", {3}},
      {CmdType::Note, "F#", {3}},
      {CmdType::Note, "G_", {3}},
      {CmdType::Note, "A_", {6}},
      {CmdType::Note, "E_", {3}},
      {CmdType::Note, "F#", {3}},
      {CmdType::Note, "G_", {6}},
      {CmdType::Note, "D_", {6}},
      {CmdType::Octave, "", {3}},
      {CmdType::Note, "A_", {3}},
      {CmdType::Octave, "", {4}},
      {CmdType::Note, "D_", {3}},
      {CmdType::Note, "E_", {6}},
      {CmdType::Octave, "", {3}},
      {CmdType::Note, "B_", {3}},
      {CmdType::Octave, "", {4}},
      {CmdType::Note, "E_", {3}},
      {CmdType::Note, "F#", {3}},
      {CmdType::Note, "G_", {3}},
      {CmdType::Note, "A_", {6}},
      {CmdType::Note, "F#", {3}},
      {CmdType::Note, "G_", {3}},
      {CmdType::Note, "A_", {6}},

      {CmdType::SoundLoop, ".mainloop", {0}}
  };
}

namespace Music_DefeatedTrainer_Ch3 {
  static const std::vector<Event> data = {
      {CmdType::NoteType, "", {4,1,0}},
      {CmdType::Octave, "", {5}},
      {CmdType::Note, "D_", {2}},
      {CmdType::Note, "D_", {2}},
      {CmdType::Note, "D_", {2}},
      {CmdType::Octave, "", {4}},
      {CmdType::Note, "B_", {2}},
      {CmdType::Note, "A_", {2}},
      {CmdType::Note, "G_", {2}},
      {CmdType::Note, "A_", {12}},

      {CmdType::NoteType, "", {4,2,1}},
      {CmdType::LoopStart, ".mainloop"},

      {CmdType::Note, "F#", {3}},
      {CmdType::Rest, "", {3}},
      {CmdType::Note, "F#", {3}},
      {CmdType::Rest, "", {3}},
      {CmdType::Note, "G#", {3}},
      {CmdType::Rest, "", {3}},
      {CmdType::Note, "G#", {3}},
      {CmdType::Rest, "", {3}},
      {CmdType::Note, "A_", {3}},
      {CmdType::Rest, "", {3}},
      {CmdType::Note, "A_", {3}},
      {CmdType::Rest, "", {3}},
      {CmdType::Note, "B_", {3}},
      {CmdType::Rest, "", {3}},
      {CmdType::Note, "B_", {3}},
      {CmdType::Rest, "", {3}},

      {CmdType::SoundLoop, ".mainloop", {0}}
  };
}