#pragma once

// DON'T EDIT - This file is auto generated by sharpmake
// Generated from code generation key 'MountingPoints'
// NOLINTBEGIN

namespace rex
{
  enum class MountingPoint
  {
    // MountingPoint values for RexEngine
    Logs /*Folder where all logs go*/,
    EngineSettings /*Root directory of engine settings*/,
    EngineMaterials /*Root directory of engine settings*/,
    EngineShaders /*Root directory of engine shaders*/,
    EngineRoot /*Root directory of engine files*/,
    ProjectRoot /*Root directory of the current project*/,
    SessionsRoot /*Root directory of all sessions*/,
    ProjectSessionsRoot /*Root directory of all sessions of this project*/,
    Session /*Root directory of the current session*/,
 
    // MountingPoint values for Pokemon
    Maps,
    Tilesets,
 
  };
} // namespace rex
// NOLINTEND
