#include <vector>
#include <string>

enum class CmdType {
  Tempo,
  Volume,
  DutyCycle,
  Vibrato,
  TogglePerfectPitch,
  NoteType,
  Octave,
  Note,
  Rest,
  LoopStart,
  LoopEnd,
  Call,
  Ret,
  SoundLoop,
  SoundCall,
  SoundRet
};

struct Event {
  CmdType type;
  std::string note;
  std::vector<int> args;
};

namespace Music_Cities2_Ch1 {
  static const std::vector<Event> data = {
      {CmdType::Tempo, "", {148}},
      {CmdType::Volume, "", {7,7}},
      {CmdType::DutyCycle, "", {3}},
      {CmdType::Vibrato, "", {8,3,2}},
      {CmdType::TogglePerfectPitch, ""},
      {CmdType::NoteType, "", {12,11,6}},
      {CmdType::Rest, "", {8}},
      {CmdType::Octave, "", {3}},
      {CmdType::Note, "E_", {2}},
      {CmdType::Note, "D#", {2}},
      {CmdType::Note, "C#", {2}},
      {CmdType::Note, "C_", {2}},
      {CmdType::Octave, "", {2}},
      {CmdType::Note, "B_", {2}},
      {CmdType::Rest, "", {14}},
      {CmdType::LoopStart, ".mainloop"},

      {CmdType::Octave, "", {3}},
      {CmdType::Note, "B_", {4}},
      {CmdType::Octave, "", {4}},
      {CmdType::Note, "C#", {2}},
      {CmdType::Note, "D#", {1}},
      {CmdType::Note, "D_", {1}},
      {CmdType::Note, "C#", {4}},
      {CmdType::Octave, "", {3}},
      {CmdType::Note, "B_", {4}},
      {CmdType::Note, "G#", {8}},
      {CmdType::Note, "E_", {8}},
      {CmdType::Note, "A_", {4}},
      {CmdType::Note, "G#", {2}},
      {CmdType::Note, "F#", {2}},
      {CmdType::Note, "G#", {2}},
      {CmdType::Note, "A_", {2}},
      {CmdType::Note, "B_", {2}},
      {CmdType::Octave, "", {4}},
      {CmdType::Note, "C#", {2}},
      {CmdType::Rest, "", {16}},
      {CmdType::Note, "C#", {4}},
      {CmdType::Octave, "", {3}},
      {CmdType::Note, "B_", {2}},
      {CmdType::Octave, "", {4}},
      {CmdType::Note, "C#", {1}},
      {CmdType::Note, "D#", {1}},
      {CmdType::Note, "C#", {4}},
      {CmdType::Octave, "", {3}},
      {CmdType::Note, "B_", {4}},
      {CmdType::Note, "E_", {1}},
      {CmdType::Note, "E_", {1}},
      {CmdType::Note, "E_", {1}},
      {CmdType::Note, "E_", {1}},
      {CmdType::Note, "E_", {1}},
      {CmdType::Rest, "", {3}},
      {CmdType::Note, "G#", {8}},
      {CmdType::Note, "B_", {4}},
      {CmdType::Note, "A_", {2}},
      {CmdType::Note, "G#", {2}},
      {CmdType::Note, "F#", {2}},
      {CmdType::Note, "G#", {2}},
      {CmdType::Note, "A_", {2}},
      {CmdType::Note, "B_", {2}},
      {CmdType::Note, "E_", {2}},
      {CmdType::Note, "F#", {2}},
      {CmdType::Note, "G#", {2}},
      {CmdType::Rest, "", {2}},
      {CmdType::Octave, "", {4}},
      {CmdType::Note, "E_", {4}},
      {CmdType::Octave, "", {3}},
      {CmdType::Note, "B_", {4}},
      {CmdType::Note, "F#", {2}},
      {CmdType::Note, "G#", {2}},
      {CmdType::Note, "A_", {2}},
      {CmdType::Rest, "", {2}},
      {CmdType::Octave, "", {4}},
      {CmdType::Note, "F#", {4}},
      {CmdType::Note, "D#", {4}},
      {CmdType::Octave, "", {3}},
      {CmdType::Note, "E_", {2}},
      {CmdType::Rest, "", {4}},
      {CmdType::Note, "F#", {2}},
      {CmdType::Rest, "", {4}},
      {CmdType::Note, "A_", {2}},
      {CmdType::Rest, "", {2}},
      {CmdType::Note, "B_", {2}},
      {CmdType::Rest, "", {16}},
      {CmdType::Rest, "", {16}},
      {CmdType::Rest, "", {14}},
      {CmdType::Note, "E_", {16}},
      {CmdType::Note, "F#", {8}},
      {CmdType::Note, "G#", {4}},
      {CmdType::Note, "F#", {4}},
      {CmdType::Note, "E_", {2}},
      {CmdType::Rest, "", {14}},
      {CmdType::SoundLoop, ".mainloop", {0}}
  };
}

namespace Music_Cities2_Ch2 {
  static const std::vector<Event> data = {
      {CmdType::DutyCycle, "", {3}},
      {CmdType::Vibrato, "", {8,2,3}},
      {CmdType::NoteType, "", {12,12,2}},
      {CmdType::Octave, "", {4}},
      {CmdType::Note, "E_", {2}},
      {CmdType::Note, "D#", {2}},
      {CmdType::Note, "C#", {2}},
      {CmdType::Octave, "", {3}},
      {CmdType::Note, "B_", {2}},
      {CmdType::Note, "A_", {2}},
      {CmdType::Note, "B_", {2}},
      {CmdType::Octave, "", {4}},
      {CmdType::Note, "C#", {2}},
      {CmdType::Note, "D#", {2}},
      {CmdType::Note, "E_", {6}},
      {CmdType::NoteType, "", {12,12,2}},
      {CmdType::DutyCycle, "", {2}},
      {CmdType::Octave, "", {4}},
      {CmdType::Note, "E_", {1}},
      {CmdType::Octave, "", {3}},
      {CmdType::Note, "B_", {1}},
      {CmdType::Octave, "", {4}},
      {CmdType::Note, "C#", {2}},
      {CmdType::Note, "D#", {2}},
      {CmdType::Note, "E_", {1}},
      {CmdType::Note, "F#", {1}},
      {CmdType::Note, "G#", {1}},
      {CmdType::Note, "A_", {1}},
      {CmdType::LoopStart, ".mainloop"},

      {CmdType::Note, "G#", {6}},
      {CmdType::NoteType, "", {12,12,2}},
      {CmdType::Note, "A_", {1}},
      {CmdType::Note, "G#", {1}},
      {CmdType::NoteType, "", {12,12,4}},
      {CmdType::Note, "F#", {14}},
      {CmdType::NoteType, "", {12,12,2}},
      {CmdType::Note, "E_", {1}},
      {CmdType::Octave, "", {3}},
      {CmdType::Note, "B_", {1}},
      {CmdType::Octave, "", {4}},
      {CmdType::Note, "C#", {2}},
      {CmdType::Note, "D#", {2}},
      {CmdType::Note, "E_", {1}},
      {CmdType::Note, "F#", {1}},
      {CmdType::Note, "G#", {1}},
      {CmdType::Note, "A_", {1}},

      {CmdType::SoundLoop, ".mainloop", {0}}
  };
}

namespace Music_Cities2_Ch3 {
  static const std::vector<Event> data = {
      {CmdType::NoteType, "", {12,1,1}},
      {CmdType::Rest, "", {16}},
      {CmdType::Octave, "", {4}},
      {CmdType::Note, "E_", {2}},
      {CmdType::Note, "G#", {2}},
      {CmdType::Note, "E_", {2}},
      {CmdType::Note, "G#", {2}},
      {CmdType::LoopStart, ".mainloop"},

      {CmdType::Note, "F#", {2}},
      {CmdType::Note, "A_", {2}},
      {CmdType::Note, "F#", {2}},
      {CmdType::Note, "A_", {2}},
      {CmdType::Note, "B_", {2}},
      {CmdType::Note, "A_", {2}},
      {CmdType::Note, "G#", {2}},
      {CmdType::Note, "F#", {2}},
      {CmdType::SoundLoop, ".mainloop", {0}}
  };
}

// ================= MUSIC CREDITS =================

namespace Music_Credits_Ch1 {
  static const std::vector<Event> data = {
      {CmdType::Tempo, "", {140}},
      {CmdType::Volume, "", {7,7}},
      {CmdType::DutyCycle, "", {3}},
      {CmdType::Vibrato, "", {8,3,4}},
      {CmdType::TogglePerfectPitch, ""},
      {CmdType::NoteType, "", {12,11,5}},
      {CmdType::Octave, "", {4}},
      {CmdType::Note, "E_", {6}},
      {CmdType::Octave, "", {3}},
      {CmdType::Note, "A_", {1}},
      {CmdType::Octave, "", {4}},
      {CmdType::Note, "E_", {1}},
      {CmdType::Note, "D_", {6}},
      {CmdType::Octave, "", {3}},
      {CmdType::Note, "G_", {1}},
      {CmdType::Octave, "", {4}},
      {CmdType::Note, "D_", {1}},
      {CmdType::Note, "C#", {6}},
      {CmdType::Octave, "", {3}},
      {CmdType::Note, "F#", {1}},
      {CmdType::Octave, "", {4}},
      {CmdType::Note, "C#", {1}},
      {CmdType::Note, "D_", {4}},
      {CmdType::Note, "E_", {2}},
      {CmdType::Note, "C#", {1}},
      {CmdType::Note, "E_", {1}},
      {CmdType::Note, "C#", {1}},
      {CmdType::Rest, "", {1}},
      {CmdType::Octave, "", {3}},
      {CmdType::Note, "E_", {1}},
  };
}

namespace Music_DefeatedGymLeader_Ch1 {
  static const std::vector<Event> data = {
      {CmdType::Tempo, "", {112}},
      {CmdType::Volume, "", {7,7}},
      {CmdType::DutyCycle, "", {3}},
      {CmdType::Vibrato, "", {18,3,1}},
      {CmdType::TogglePerfectPitch, ""},
      {CmdType::NoteType, "", {12,10,6}},
      {CmdType::Octave, "", {4}},
      {CmdType::Note, "D_", {6}},
      {CmdType::Octave, "", {3}},
      {CmdType::Note, "A_", {1}},
      {CmdType::Octave, "", {4}},
      {CmdType::Note, "D_", {1}},
      {CmdType::Note, "F#", {6}},
      {CmdType::Note, "D_", {1}},
      {CmdType::Note, "F#", {1}},
      {CmdType::Note, "A_", {8}},
      {CmdType::LoopStart, ".mainloop"}
  };
}