#pragma once

// DON'T EDIT - This file is auto generated by sharpmake
// Generated from code generation key 'CommandLineArgs'
// NOLINTBEGIN

#include "rex_engine/cmdline.h"
#include "rex_std/array.h"
namespace rex
{
  inline rsl::array g_command_line_args = 
  {
    // cmdline::Argument values for RexEngine - using code generation key: 'CommandLineArgs'
    cmdline::Argument{ "Root", "The directory to initialize the vfs with. this is similar as setting the working root directory", "RexEngine" },
    cmdline::Argument{ "Help", "This will list all command line arguments for the executable", "RexEngine" },
    cmdline::Argument{ "LogLevel", "Specify log level per logger (eg. -LogLevel=Engine=trace,Renderer=info)", "RexEngine" },
    cmdline::Argument{ "BreakOnBoot", "Break on boot so you can attach a debugger", "RexEngine" },
    cmdline::Argument{ "AttachOnBoot", "Attach the debugger on boot", "RexEngine" },
 
  };
} // namespace rex
// NOLINTEND
