

# This file was automatically generated by "create_project.py"
# Command: generate_project(type project_name solution_folder project_folder pch_header_name = project_folder pch_src_name = project_folder)
# Example: generate_project(static CoreLibs 1_common core_libs)


# include path: ${CMAKE_SOURCE_DIR}/source/include/1_engine/engine
# src path: ${CMAKE_SOURCE_DIR}/source/src/1_engine/engine


# Project Name Project
# -------------------------
file(GLOB_RECURSE Engine_LIBS_INC    ${CMAKE_SOURCE_DIR}/source/include/1_engine/engine/*.h)
file(GLOB_RECURSE Engine_LIBS_SRC    ${CMAKE_SOURCE_DIR}/source/src/1_engine/engine/*.cpp)


# Create the project filters
GROUPSOURCES(${CMAKE_SOURCE_DIR}/source/include/1_engine/engine include)
GROUPSOURCES(${CMAKE_SOURCE_DIR}/source/src/1_engine/engine src)


# Create the project
add_library(Engine STATIC ${Engine_LIBS_INC} ${Engine_LIBS_SRC})

# Set the include directories
target_include_directories(Engine PUBLIC ${CMAKE_SOURCE_DIR}/source/include/1_engine/engine)
target_include_directories(Engine PUBLIC ${REX_STL_DIR}/source/include/1_Core)

# Set the link libraries
target_link_libraries(Engine PUBLIC RexStd)

# Set project properties
set_target_properties(Engine PROPERTIES FOLDER                                         1_engine)   		# solution folder
set_target_properties(Engine PROPERTIES DEFINE_SYMBOL                                  "" )                     		# defines
IF(MSVC)
	set_property(TARGET Engine PROPERTY VS_DEBUGGER_WORKING_DIRECTORY                ${OUTPUT_BINDIR})        		# working directory
	set_target_properties(Engine PROPERTIES ARCHIVE_OUTPUT_DIRECTORY 					  ${OUTPUT_BINDIR})				# output directory
    set_target_properties(Engine PROPERTIES LIBRARY_OUTPUT_DIRECTORY 					  ${OUTPUT_BINDIR})				# output directory
    set_target_properties(Engine PROPERTIES RUNTIME_OUTPUT_DIRECTORY 					  ${OUTPUT_BINDIR})				# output directory


	if (REX_UNITY) # unity builds on visual studio
		set_target_properties(Engine PROPERTIES VS_GLOBAL_EnableUnitySupport                 True)                    		
		set_target_properties(Engine PROPERTIES VS_GLOBAL_IncludeInUnityFile                 True)
		set_target_properties(Engine PROPERTIES VS_GLOBAL_OrderInUnityFile                   100)
		set_target_properties(Engine PROPERTIES VS_GLOBAL_CombineFilesOnlyFromTheSameFolder  false)
		set_target_properties(Engine PROPERTIES VS_GLOBAL_MinFilesInUnityFile                2)
		set_target_properties(Engine PROPERTIES VS_GLOBAL_MaxFilesInUnityFile                0)
		set_target_properties(Engine PROPERTIES VS_GLOBAL_MinUnityFiles                      1)
		set_target_properties(Engine PROPERTIES VS_GLOBAL_UnityFilesDirectory                .)
	ENDIF()
ENDIF()


# Compiler options
target_compile_options(Engine PRIVATE /W4 /WX /MP)


# Set precompiled header
add_precompiled_header(Engine "engine_pch.h" "engine_pch.cpp")