#pragma once

namespace rex
{
	namespace gfx
	{
    // The type a variable in a shader can be
		enum class ShaderVariableType
		{
      Void = 0,
      Bool = 1,
      Int = 2,
      Float = 3,
      String = 4,
      Texture = 5,
      Texture1d = 6,
      Texture2d = 7,
      Texture3d = 8,
      TextureCube = 9,
      Sampler = 10,
      Sampler1d = 11,
      Sampler2d = 12,
      Sampler3d = 13,
      SamplerCube = 14,
      PixelShader = 15,
      VertexShader = 16,
      PixelFragment = 17,
      VertexFragment = 18,
      Uint = 19,
      Uint8 = 20,
      GeometryShader = 21,
      Rasterizer = 22,
      DepthStencil = 23,
      Blend = 24,
      Buffer = 25,
      CBuffer = 26,
      TBuffer = 27,
      Texture1dArray = 28,
      Texture2dArray = 29,
      RenderTargetView = 30,
      DepthStencilView = 31,
      Texture2dms = 32,
      Texture2dmsArray = 33,
      TextureCubeArray = 34,
      HullShader = 35,
      DomainShader = 36,
      InterfacePointer = 37,
      ComputeShader = 38,
      Double = 39,
      Rwtexture1d = 40,
      Rwtexture1dArray = 41,
      Rwtexture2d = 42,
      Rwtexture2dArray = 43,
      Rwtexture3d = 44,
      RwBuffer = 45,
      ByteAddressBuffer = 46,
      RwByteAddressBuffer = 47,
      StructuredBuffer = 48,
      RwstructuredBuffer = 49,
      AppendStructuredBuffer = 50,
      ConsumeStructuredBuffer = 51,
      Min8float = 52,
      Min10float = 53,
      Min16float = 54,
      Min12int = 55,
      Min16int = 56,
      Min16uint = 57,
		};
	}
}